name: Checkov composite action
description: |-
  Run [`checkov`](https://www.checkov.io) static analysis.
inputs:
  directory:
    description: The directory to scan (default scans entire repository).
    required: false
    default: '.'
  output_format:
    description: The output format.
    required: false
    default: 'sarif'
  fail_workflow:
    description: Return an error code if there are failed checks.
    required: false
    default: 'true'
  
runs:
  using: 'composite'
  steps:
    - name: Checkov
      uses: bridgecrewio/checkov-action@69e494e1b28dc24ec680e7ed364e0c227e2026bf	# v12.2743.0
      with:
        directory: ${{ inputs.directory }}
        soft_fail: ${{ inputs.fail_workflow == 'true' && 'false' || 'true' }}
        output_format: ${{ inputs.output_format }}
        output_file_path: checkov-sarif.results,
        framework: all
        quiet: true
        compact: true
    - name: Convert SARIF to Markdown
      uses: ./sarif-to-markdown
      if: success() || failure()
      with:
        sarif_file_path: checkov-sarif.results
    - name: Post/Update PR Comment
      uses: ./pr-comment
      if: success() || failure()
      with:
        document_txt_path: sarif_converted.md
        pr_comment_title: '🔒 Checkov Security Scan Results'
