name: Grype composite action
description: |-
  Run [`grype`](https://github.com/anchore/grype) static analysis.
inputs:
  # registry:
  #   description: 'The registry where the container will be stored'
  #   required: true
  #   default: 'localbuild'
  # image_name:
  #   description: 'The name of the image to build'
  #   required: true
  #   default: 'testimage'
  image_id:
    description: 'The ID of the image to scan'
    required: true
  output_format:
    description: The output format.
    required: false
    default: 'sarif'
  fail_workflow:
    description: Return an error code if there are failed checks.
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    # - name: build local container
    #   uses: docker/build-push-action@v4
    #   with:
    #     tags: ${{ inputs.registry }}/${{ inputs.image_name }}
    #     push: false
    #     load: true

    - name: Scan image
      uses: anchore/scan-action@3aaf50d765cfcceafa51d322ccb790e40f6cd8c5 # v7.2.0
      with:
        image: ${{ inputs.image_id }} # ${{ inputs.registry }}/${{ inputs.image_name }}
        fail-build: ${{ inputs.fail_workflow }}
        output-format: ${{ inputs.output_format }}
        output-file: grype-results.sarif
        severity-cutoff: critical
        only-fixed: true
    - name: Convert SARIF to Markdown
      uses: ./sarif-to-markdown
      if: success() || failure()
      with:
        sarif_file_path: grype-results.sarif
    - name: Post/Update PR Comment
      uses: ./pr-comment
      if: success() || failure()
      with:
        document_txt_path: sarif_converted.md
        pr_comment_title: '🔒 Grype Image Security Scan Results'
