name: TruffleHog composite action
description: |-
  Run [`TruffleHog`](https://trufflesecurity.com/) secrets detection.
inputs:
  fail-on-valid-secret:
    description: Fail the secret-scan job if a new valid secret is detected (recommended).
    required: false
    default: "true"
runs:
  using: 'composite'
  steps:
    - name: TruffleHog OSS
      id: trufflehog
      uses: trufflesecurity/trufflehog@v3.90.1
      continue-on-error: true
      with:
        path: ./
        base: "${{ github.event.repository.default_branch }}"
        head: HEAD
        version: 3.90.1
    - name: TruffleHog Scan Results Success
      shell: bash
      if: steps.trufflehog.outcome != 'failure'
      run: |
        python - <<EOF
        comment_body = "### TruffleHog Scan Results\n\n"
        comment_body += "No new secrets found.\n\n"

        with open("comment.md", "a") as file:
            file.write(comment_body)
        EOF
    - name: TruffleHog Scan Results Failure
      shell: bash
      if: steps.trufflehog.outcome == 'failure'
      run: |
        python - <<EOF
        import os

        github_repository = os.getenv('GITHUB_REPOSITORY')
        github_ref = os.getenv('GITHUB_REF')

        pr_number = github_ref.split('/')[-2]

        files_changed_url = f"https://github.com/{github_repository}/pull/{pr_number}/files"

        comment_body = "### TruffleHog Scan Results\n\n"
        comment_body += "**Valid secrets found!**\n\n Please check [Files changed](" + files_changed_url + ") tab in PR to see identified secrets then remove and rotate.\n\n"

        with open("comment.md", "a") as file:
            file.write(comment_body)
        EOF
    - name: Post/Update PR comment
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const results = fs.readFileSync('comment.md', 'utf8');

          // 1. Retrieve existing bot comments for the PR
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          })
          const botComment = comments.find(comment => {
            return comment.user.type === 'Bot' && comment.body.includes('TruffleHog Scan Results')
          })

          // 2. If we have a comment, update it, otherwise create a new one
          if (botComment) {
            github.rest.issues.updateComment({
              ...context.repo,
              comment_id: botComment.id,
              body: results
            })
          } else {
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: results
            })
          }
    - name: Scan Results Status
      shell: bash
      if: steps.trufflehog.outcome == 'failure'
      run: |
        if [ ${{ inputs.fail-on-valid-secret }} == "true" ]
        then
          exit 1
        fi
