name: Checkov Scan

permissions:
  contents: read
  pull-requests: write

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  checkov_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          soft_fail: true  # don't want to fail the step, because of found findings
          quiet: true
          output_format: json
          output_file_path: ./checkov_results.json,


      - name: Report Checkov results
        if: github.event_name == 'pull_request'
        run: |
          echo "Preparing Checkov results"
          python - <<EOF
          import json
          import sys

          with open('checkov_results.json') as f:
            results = json.load(f)

          comment_body = '### Checkov Scan Results\n'

          for result in results:
            if len(result['results']['failed_checks']) > 0:
              for failed_check in result['results']['failed_checks']:
                check_id        = failed_check['check_id']
                check_name      = failed_check['check_name']
                # severity      = failed_check['severity'] # Removed as always null
                file_path       = failed_check['file_path']
                file_line_start = failed_check['file_line_range'][0]
                file_line_end   = failed_check['file_line_range'][1]
                guideline       = failed_check['guideline']
                comment_body    += f'- **{file_path}:{file_line_start}-{file_line_end}** - {check_id} - {check_name} - {guideline}\n'

          try:
            check_id
          except NameError:
            comment_body += "No issues found."
          
          with open('checkov_comment.md', 'w') as file:
            file.write(comment_body)
          EOF

      - name: Post comment with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('checkov_comment.md', 'utf8');
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: results
            });