name: Trivy Scan

permissions:
  contents: read
  pull-requests: write

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          hide-progress: true
          format: 'json'