name: Trivy Scan

permissions:
  contents: read
  pull-requests: write

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          scanners: 'vuln,misconfig,secret'
          hide-progress: true
          format: 'json'
          scan-ref: 'src'
          # output: 'trivy_results.json'
      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy_results.json ]]; then
            {
              echo "### Security Output"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy_results.json
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi