name: TruffleHog Scan

on:
  pull_request: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history for all branches and tags

      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          path: ./
          base: "${{ github.event.repository.default_branch }}"
          head: HEAD
          extra_args: --json

      # - name: Scan Results Status
      #   if: steps.trufflehog.outcome == 'failure'
      #   run: exit 1